services:
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_DB=litedb
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    restart: no
    ports:
      - '5432:5432'